---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  yamllint .
  ansible-lint .

platforms:
  - name: zookeeper
    hostname: zookeeper
    image: idealista/zookeeper:latest
    privileged: false
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    groups:
      - zookeeper
    command: '/lib/systemd/systemd'
    stop_signal: 'RTMIN+3'
    networks:
      - name: kafka-network
    published_ports:
      - 0.0.0.0:2181:2181/tcp

  - name: kafka1
    hostname: kafka1
    image: idealista/jdk:8u302-bullseye-corretto-headless
    privileged: false
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    groups:
      - kafka
    command: '/lib/systemd/systemd'
    stop_signal: 'RTMIN+3'
    networks:
      - name: kafka-network
    published_ports:
      - 0.0.0.0:9999:9999/tcp

  - name: kafka2
    hostname: kafka2
    image: idealista/jdk:8u302-bullseye-corretto-headless
    privileged: false
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    groups:
      - kafka
    command: '/lib/systemd/systemd'
    stop_signal: 'RTMIN+3'
    networks:
      - name: kafka-network
    published_ports:
      - 0.0.0.0:9998:9999/tcp

  - name: kafka3
    hostname: kafka3
    image: idealista/jdk:8u302-bullseye-corretto-headless
    privileged: false
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    groups:
      - kafka
    command: '/lib/systemd/systemd'
    stop_signal: 'RTMIN+3'
    networks:
      - name: kafka-network
    published_ports:
      - 0.0.0.0:9997:9999/tcp

provisioner:
  name: ansible
  lint:
    - name: ansible-lint
    - name: yamllint
  log: True

scenario:
  name: default

verifier:
  name: ansible
